# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed1d36e46bf1aa959521301f9361f96179b2b465990444273b8ef592694704b24eda3e0986f99bf58c28b96963d7dc0405d128e7baab0b11aea86ee77c63ea5d

test:
  secret_key_base: a59e86d53b49e18afd9585765252fc86025c83141870b81fcc0de21781e0d919dc2530b9944a556daf32cf4f1b9eb0775d5f5e9c88780386993eaa31ac113587

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
